language: node_js
node_js:
  - "4.3"
  - "4.0"
  - "0.12"
  - "0.10"

addons:
  browserstack:
    username: "pankajahuja2"
    access_key:
      secure: "e0yj4p67e3j+bsO07RPLtrR6Pft0SUVYwEexeF3Ob+VeNfyMJ4m40Wod9p+mEURHnDmGltbT9s7kHfWwijURTme03FRtXIyLDmW2NjWK5mZ8855DqQEAQk9EVjHTRGemewp3WLU7BUQuUvVmt/Kex9xu2n6HegO/88+vhpXt6B1jYSsAyVAkbwv4CrO87frRdO7/wcoCkEz2vwjUSdCnX7Ir5rNrHdEi4yjOm7L+d+hdXM4ONH8hEWltQGbIae1QKQy052TrYOVel0CK1+Snej9s72va48kOFB0Phe5ZnqjjK2BbiAUpPbCRTh4seXXiFkBERWx5q6vZyfgeTbXB1Rdjw1hcJwSwrnehtIs2Y8HeeV2atweR1pXBRBsfetdUqOtpSEk+zHKfsp1jn0jhTwIXeIdD7vAGCwd+cynaowpilvyXf6tk/hUtyfDLZgMR6yaOPV790Vz/XikBJNxXtLr9PG3YhBmttd8o7b+QBAo9Ublo3xvQ4Mzj5Ee2EykUA5byDplngKJE+6p4BmCL0D1O3jrVmkISfa1nnkU4j7/gnU0OgUfSASnjS7rKa6e2v5Gj3HvRPT02VTzAMbUEKYTdygYJq3AlMG9AIHItCGuxi74i9E7qkYFDy6QE074gSY09k3gIcQdyZdCHY6jCdfH/jPyFBnoXxRyPt2EIxlY=":
