language: node_js
node_js:
  - "4.3"

addons:
  browserstack:
    username: "pankajahuja1"
    access_key:
      secure: "VjowvVpa5+N+1lUPlvhkvXGcSPEAvNj3xeFs0xMuRIZwRocAmoKnB2htLXFc+c7FS5PRncwuvoir0ibzODJC5soqE6RQ4tYWiEMm20y3fYirMAt3+qBbxohhu6eK0r6eJRBFqdNfMQMaUXlqv9mfm8Mk8UrAjrwV07vnjgJ6Sdhwux3sE0iPFJrrgw17ksthptFDCEp3vkahwQqyzlJWPLmrcWqxqDYiYC0ltHMZffPYKYnMSpSNISSRKvAMn9iI6STvG9/ZbLiYtE7wq5wPkuEGON8bwF2/QibbqDavbvlqKoEu2Nl8myd141sTbrN84pOWkoyWFqmAqg4YDCRdQ8cksa3B3but5ICgCzIRLkvwNMzpeBM368EHCuN2f+ZDAwdTHCYJaaLR4eZjnJ+D+eTuQwBAHGkrrjPTicyD1njDZee8j9Arq3vQH9xy8JfRJz0tnp9VfgpD1k1IumpF+lbYs/D4kErcdz33oBSY8mjWgPOz2b1nBRMbaBFY3T2uLGQGqpdxirt7QpWXMXaAs/yjEQO3ihXl+pmPiwS3OeiHS1DnCggnTF4DkSxRT0www3kdSHnA6rpkdV6KqDKPsFlC2BWBco8ECxlRXeWOCH4lReZOaw77BS46STnxi5O1WQsA/HRThVZQxtpDkzXQjrm4QEw1rXXnQSuB4nNRk2s="
